baseURL = "https://kingcrimson50.com/"
languageCode = "en-us"
title = "King Crimson @ 50"

theme = "hugo-theme-massively"

# Below parameters can be set to override default post settings
 [params.posts]
     foldername = "posts"
     pagesize = "6"
     featuredpost = "true"
